---
id: mvnd
name: Maven Daemon
defaultVersion: 0.8.0
layout: directory
packaging: ZIP_STRIP
executable: mvnd
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
  arm64: amd64
# https://github.com/apache/maven-mvnd/releases/download/0.8.0/maven-mvnd-0.8.0-darwin-amd64.zip
# https://github.com/apache/maven-mvnd/releases/download/0.8.0/maven-mvnd-0.8.0-linux-amd64.zip
urlTemplate: https://github.com/apache/maven-mvnd/releases/download/{version}/maven-mvnd-{version}-{os}-{arch}.zip