---
id: goreleaser
name: goreleaser
sources:
  - https://github.com/goreleaser/goreleaser/releases
defaultVersion: 1.10.3
layout: file
executable: goreleaser
packaging: TARGZ
osMappings:
  Darwin: Darwin
  Linux: Linux
archMappings:
  x86_64: x86_64
  arm64: arm64
urlTemplate: "https://github.com/goreleaser/goreleaser/releases/download/v{version}/goreleaser_{os}_{arch}.tar.gz"
