---
id: dyff
name: dyff
sources:
  - https://github.com/homeport/dyff/releases
defaultVersion: 1.5.4
layout: file
executable: dyff
packaging: TARGZ
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
  arm64: arm64
urlTemplate: "https://github.com/homeport/dyff/releases/download/v{version}/dyff_{version}_{os}_{arch}.tar.gz"