---
id: go
name: Go
defaultVersion: 1.18.4
layout: directory
paths: bin
executable: go
packaging: TARGZ_STRIP
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
  arm64: arm64
# https://go.dev/dl/go1.18.4.darwin-amd64.tar.gz
# https://go.dev/dl/go1.18.4.darwin-arm64.tar.gz
# https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
# https://go.dev/dl/go1.18.4.linux-arm64.tar.gz
urlTemplate: https://go.dev/dl/go{version}.{os}-{arch}.tar.gz
