---
id: provisio
name: Provisio
defaultVersion: 0.0.10
layout: file
executable: provisio
packaging: FILE
urlTemplate: https://github.com/jvanzyl/provisio-tools/releases/download/{version}/provisio-{os}-{arch}