---
id: cosign
name: cosign
sources:
- https://github.com/sigstore/cosign/releases
defaultVersion: 1.10.0
layout: file
executable: cosign
packaging: FILE
osMappings:
  Darwin: darwin
archMappings:
  x86_64: amd64
  arm64: arm64
# https://github.com/sigstore/cosign/releases/download/v1.10.0/cosign-darwin-arm64
# https://github.com/sigstore/cosign/releases/download/v1.10.0/cosign-linux-arm64
urlTemplate: "https://github.com/sigstore/cosign/releases/download/v{version}/cosign-{os}-{arch}"
