---
id: cr
name: Chart Releaser
defaultVersion: 1.4.0
executable: cr
layout: file
packaging: TARGZ
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
  arm64: arm64
# Inconsisten version
# https://github.com/helm/chart-releaser/releases/download/v1.4.0/chart-releaser_1.4.0_darwin_amd64.tar.gz
# https://github.com/helm/chart-releaser/releases/download/v1.4.0/chart-releaser_1.4.0_linux_amd64.tar.gz
# https://github.com/helm/chart-releaser/releases/download/v1.4.0/chart-releaser_1.4.0_darwin_arm64.tar.gz
# https://github.com/helm/chart-releaser/releases/download/v1.4.0/chart-releaser_1.4.0_linux_arm64.tar.gz
urlTemplate: https://github.com/helm/chart-releaser/releases/download/v{version}/chart-releaser_{version}_{os}_{arch}.tar.gz
