---
id: java
name: Java
defaultVersion: "jdk-11.0.12+7"
layout: directory
paths: Contents/Home/bin
executable: java
packaging: TARGZ_STRIP
pathManagedBy: jenv
osMappings:
  Darwin: mac
  Linux: linux
archMappings:
  x86_64: x64
  arm64: aarch64
fileNameFromContentDisposition: true
urlTemplate: https://api.adoptium.net/v3/binary/version/{version}/{os}/{arch}/jdk/hotspot/normal/eclipse?project=jdk
