---
id: graalvm
name: GraalVM
defaultVersion: 22.2.0
layout: directory
paths: Contents/Home/bin
executable: java
packaging: TARGZ_STRIP
pathManagedBy: jenv
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: amd64
  arm64: aarch64
# https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java11-darwin-amd64-21.1.0.tar.gz
# https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java11-linux-amd64-21.1.0.tar.gz
# https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-darwin-aarch64-22.2.0.tar.gz
# https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-linux-aarch64-22.2.0.tar.gz
urlTemplate: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-{version}/graalvm-ce-java17-{os}-{arch}-{version}.tar.gz
