---
id: gitleaks
name: gitleaks
sources:
  - https://github.com/zricethezav/gitleaks/releases
defaultVersion: 8.9.0
layout: file
executable: gitleaks
packaging: TARGZ
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: x64
  arm64: arm64
urlTemplate: "https://github.com/zricethezav/gitleaks/releases/download/v{version}/gitleaks_{version}_{os}_{arch}.tar.gz"

