---
id: pulumi
name: pulumi
defaultVersion: 3.22.1
layout: directory
executable: pulumi
packaging: TARGZ_STRIP
paths: .
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: x64
  arm64: arm64
urlTemplate: https://github.com/pulumi/pulumi/releases/download/v{version}/pulumi-v{version}-{os}-{arch}.tar.gz

