---
id: kubectl-slice
name: kubectl-slice
defaultVersion: 1.1.0
layout: file
executable: kubectl-slice
packaging: TARGZ
osMappings:
  Darwin: darwin
  Linux: linux
archMappings:
  x86_64: x86_64
  arm64: arm64
urlTemplate: "https://github.com/patrickdappollonio/kubectl-slice/releases/download/v{version}/kubectl-slice_{version}_{os}_{arch}.tar.gz"
