name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./mvnw clean package -DskipTests -Pnative
      - run: mv target/provisio-tools-*-runner target/provisio-Darwin-x86_64
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/provisio-Darwin-x86_64"
          token: ${{ secrets.GITHUB_TOKEN }}
