name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./mvnw clean package -B -DskipTests -Pnative
      - run: |
          os=$(uname)
          arch=$(uname -m)
          mv target/provisio-tools-*-runner target/provisio-${os}-${arch}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/provisio-*-x86_64"
          token: ${{ secrets.GITHUB_TOKEN }}
